config/routes.rb
Rails.application.routes.draw do
  root to: "galleries#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  resources :galleries do
    resources :images
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy]
  end

  resources :groups, only: [:destroy, :index, :new, :create, :show, :edit, :update] do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :image

  validates :content, presence: true

  def self.by_most_recent
    order(created_at: :desc)
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships

  has_and_belongs_to_many :images

  validates :name, :description, presence: true

  def add_member(user)
    users << user
  end

  def remove_member(user)
    users.delete(user)
  end

end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user

  validates :user, uniqueness: { scope: :group }
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  belongs_to :user
  has_many :comments
  has_many :likes

  has_and_belongs_to_many :groups

  validates :name, :description, :url, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :image
  belongs_to :user

  validates :user, uniqueness: { scope: :image }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :group_memberships
  has_many :groups, through: :group_memberships
  has_many :images
  has_many :likes
  has_many :liked_images, through: :likes, source: :image

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def like(image)
    liked_images << image
  end

  def unlike(image)
    liked_images.delete(image)
  end

  def liked?(image)
    liked_images.include? image
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  
  before_action :require_login

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @image = Image.find(params[:image_id])
    @comment = @image.comments.create(comment_params)

    if @comment.save
      redirect_to [@image.gallery, @image]
    else
      render "images/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to gallery_path(@gallery)
    else
      render :new
    end
  end

  def edit
    @gallery = find_gallery
  end

  def update
    @gallery = find_gallery

    if @gallery.update(gallery_params)
      redirect_to gallery_path(@gallery)
    else
      render :edit
    end
  end

  def show
    @gallery = find_gallery
  end

  def destroy
    @gallery = find_gallery
    @gallery.destroy

    redirect_to galleries_path
  end

  private

  def gallery_params
    params.require(:gallery).permit(:name, :description)
  end

  def find_gallery
    Gallery.find(params[:id])
  end
end

app/controllers/group_memberships_controller.rb
class GroupMembershipsController < ApplicationController

  def create
    @group = Group.find(params[:id])
    @group.add_member(current_user)

    redirect_to @group
  end

  def destroy
    @group = Group.find(params[:id])
    @group.remove_member(current_user)

    redirect_to @group
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.save
    @group.add_member(current_user)

    if @group.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
    @gallery = find_gallery
    @image = @gallery.images.new
  end

  def create
    @gallery = find_gallery
    @image = @gallery.images.new(image_params)

    if @image.save
      redirect_to gallery_image_path(@gallery, @image)
    else
      render :new
    end
  end

  def show
    @gallery = find_gallery
    @image = @gallery.images.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @gallery = find_gallery
    @image = @gallery.images.find(params[:id])
  end

  def update
    @gallery = find_gallery
    @image = @gallery.images.find(params[:id])

    if @image.update(image_params)
      redirect_to [@gallery, @image]
    else
      render :edit
    end
  end

  def destroy
    gallery = find_gallery
    image = gallery.images.find(params[:id])
    image.destroy

    redirect_to gallery
  end

  private

  def image_params
    params.require(:image).permit(:name, :description, :url, group_ids: []).merge(user: current_user)
  end

  def find_gallery
    Gallery.find(params[:gallery_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @image = Image.find(params[:image_id])
    current_user.like(@image)

    redirect_to [@image.gallery, @image]
  end

  def destroy
    @image = Image.find(params[:image_id])
    current_user.unlike(@image)

    redirect_to [@image.gallery, @image]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages.html.erb
<% if errors.any? %>
  <div>
    <p>We could not save because: </p>
    <ul><% errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<div>
  <%= comment.content %>
</div>
<div>
  - Authored by: <%= comment.user.email %>; created at 
  <%= time_ago_in_words(comment.created_at) %>
</div>
<p> </p>

app/views/galleries/_form.html.erb
<%= form_for gallery, data: {confirm: "Are you sure?"} do |form| %>

  <div>
    <%= form.label :name, "Gallery Name: " %>
    <%= form.text_field :name %>
  </div>
  <br>
  <div>
    <%= form.label :description, "Gallery Description: " %>
    <%= form.text_area :description %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Edit the <%= @gallery.name %> Gallery</h1>

<%= render "form", gallery: @gallery, errors: @gallery.errors %>

app/views/galleries/index.html.erb
<h1>Welcome to Our Photo Gallery</h1>

<div>
  <ol>
    <h3>
      <% @galleries.each do |gallery| %>
        <li><%= link_to gallery.name, gallery_path(gallery) %></li>
      <% end %>
    </h3>
  </ol>
</div>

<br>

<div>
  <h4>Don't want to view any of those galleries, then you can: </h4>
  <ul>
    <li>
      <h4><%= link_to "Create New Gallery", new_gallery_path %></h4>
    </li>
    <li>
      <h4><%= link_to "Groups", groups_path %></h4>
    </li>
  </ul>
</div>

app/views/galleries/new.html.erb
<h1>Create a New Gallery</h1>

<%= render "application/error_messages", errors: @gallery.errors %>

<%= render "form", gallery: @gallery %>

app/views/galleries/show.html.erb
<h1>The <%= @gallery.name %> Gallery</h1>

<h3><%= @gallery.description %></h3>

<br>

<% @gallery.images.each do |image| %>
  <div>
    <%= link_to (image_tag image.url), gallery_image_path(@gallery, image) %>
  </div>
<% end %>

<div>
  <h4>Other options: </h4>
  <ul>
    <h4>
      <li>Return to
        <%= link_to "Gallery List", galleries_path %>
      </li>
      <br>
      <li>Add an
        <%= link_to "Image", new_gallery_image_path(@gallery) %>
      </li>
      <br>
      <li>Edit the
        <%= link_to "#{@gallery.name} Gallery", edit_gallery_path(@gallery) %>
      </li>
      <br>
      <li>
        <%= button_to "Delete Gallery", gallery_path(@gallery), method: :delete %>
      </li>
    </h4>
  </ul>
</div>

app/views/groups/_form.html.erb
<div>
  <%= form_for group do |form| %>
    <div>
      <%= form.label :name, "Group Name: " %>
      <%= form.text_field :name %>
    </div>
    <br>
    <div>
      <%= form.label :description, "Group Description: " %>
      <%= form.text_area :description %>
    </div>
    <br>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Edit <%= @group.name %> Group</h1>

<%= render "application/error_messages", errors: @group.errors %>

<%= render "form", group: @group %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<div>
  <ol>
    <% @groups.each do |group| %>
      <li><%= link_to group.name, group %></li>
    <% end %>
  </ol>
</div>

<br>

<div>
  <h4>Other options: 
    <ul>
      <li><%= link_to "Create New Group", new_group_path %></li>
      <br>
      <li><%= link_to "Back to Home", root_path  %></li>
    </ul>
  </h4>
</div>

app/views/groups/new.html.erb
<h1>Create a New Group</h1>

<%= render "application/error_messages", errors: @group.errors %>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<h1>The <%= @group.name %> Group</h1>

<p><%= @group.description %></p>
<br>
<div>
  <h4>
    <ol>
      <% @group.users.each do |user| %>
        <li><%= user.email %></li>
      <% end %>
    </ol>
  </h4>
</div>

<br>

<div>
  <% if @group.users.include?(current_user) %>
    <h4>You're a member of this group!</h4>
    <%= button_to "Leave Group", leave_group_path(@group), method: :delete %>
    <div><h4>Other options: </h4>
      <ul>
        <li>
          <h4><%= link_to "Edit Group", edit_group_path(@group) %></h4>
        </li>
        <li>
          <h4><%= button_to "Delete Group", @group, method: :delete %></h4>
        </li>
      </ul>
    </div>
  <% else %>
    <%= button_to "Join Group", join_group_path(@group), method: :post %>
    <h4>Other options: </h4>
  <% end %>
</div>

<div>
  <ul>
    <li>
      <h4><%= link_to "Return to Groups", groups_path %></h4>
    </li>
  </ul>
</div>

app/views/images/_form.html.erb
<%= form_for [gallery, image], data: {confirm: "Are you sure?"} do |form| %>
  <div>
    <%= form.label :name, "Image Name: " %>
    <%= form.text_field :name %>
  </div>
  <br>
  <div>
    <%= form.label :description, "Image Description: " %>
    <%= form.text_area :description %>
  </div>
  <br>
  <div>
    <%= form.label :url, "URL: " %>
    <%= form.text_field :url %>
  </div>
  <br>
  <div>
    <%= form.collection_check_boxes :group_ids, current_user.groups, :id, :name %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Edit the <%= @image.name %> Image</h1>

<%= render "application/error_messages", errors: @image.errors %>

<%= render "form", gallery: @gallery, image: @image %>

app/views/images/new.html.erb
<h1>Create New Image</h1>

<%= render "application/error_messages", errors: @image.errors %>

<%= render "form", gallery: @gallery, image: @image, errors: @image.errors %>

app/views/images/show.html.erb
<h1>The <%= @image.name %> Image</h1>

<%= image_tag @image.url %>

<div><h4>Groups a part of: </h4>
  <ul>
    <% @image.groups.each do |group| %>
      <li><%= group.name %></li>
    <% end %>
  </ul>
</div>

<div>
  <% if current_user.liked? @image %>
    <%= button_to "Unlike Image", image_like_path(@image), method: :delete %>
  <% else %>
    <%= button_to "Like Image", image_like_path(@image) %>
  <% end %>
</div>

<br>

<div>
  <%= render @image.comments.by_most_recent %>
</div>

<div>
  <%= form_for [@image, @comment], data: {confirm: "Are you sure?"} do |form| %>
    <div>
    <%= form.label :content, "Comment: " %>
    <%= form.text_area :content %>
    </div>
    <p> </p>
    <div>
    <%= form.submit %>
    </div>
  <% end %>
</div>

<br>

<div>
  <h4>Other options: </h4>
  <ul>
    <h4>
      <li>Return to
        <%= link_to "#{@image.gallery.name} Gallery", gallery_path(@image.gallery) %>
      </li>
      <br>
      <li>Edit the
        <%= link_to "#{@image.name} Image", edit_gallery_image_path(@image.gallery, @image) %>
      </li>
      <br>
      <li>
        <%= button_to "Delete Image", gallery_image_path(@image.gallery, @image), method: :delete %>
      </li>
    </h4>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fotobum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <% if current_user %>
      <p><b>Welcome: 
      <%= link_to " #{current_user.email}", user_path(current_user) %>
      <%= button_to "Sign Out", session_path, method: :delete %>
      </b></p>
    <% else %>
      <p>
      <%= link_to "Sign Up", new_user_path %>
      or 
      <%= link_to "Sign In", new_session_path %>
      </p>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Images for <%= @user.email %></h1>

<% @user.images.each do |image| %>
  <div>
    <%= image_tag image.url %>
  </div>
<% end %>

<div>
  <ul><h4>
    <li>Return to
      <%= link_to "Gallery Home", galleries_path %>
    </h4></li>
  </ul>
</div>